-- Schema voor Bestelbeheersysteem

CREATE TABLE IF NOT EXISTS test_entity (
    id    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value VARCHAR(255)
);
-- Uitgevoerd via Spring Boot SQL-initialisatie (plain JDBC, auto-commit).
-- Draait VOOR JPA-initialisatie en VOOR InitialDataSetup.

CREATE TABLE IF NOT EXISTS gebruiker (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gebruikersnaam  VARCHAR(255)  NOT NULL,
    wachtwoord      VARCHAR(255)  NOT NULL,
    email           VARCHAR(255)  NOT NULL,
    voornaam        VARCHAR(255)  NOT NULL,
    achternaam      VARCHAR(255)  NOT NULL,
    CONSTRAINT uk_gebruikersnaam UNIQUE (gebruikersnaam)
);

CREATE TABLE IF NOT EXISTS product (
    id              BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    naam            VARCHAR(255)   NOT NULL,
    beschrijving    VARCHAR(1000),
    prijs           DECIMAL(10, 2) NOT NULL,
    stock           INT            NOT NULL
);

CREATE TABLE IF NOT EXISTS bestelling (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    datum           TIMESTAMP     NOT NULL,
    status          VARCHAR(50)   NOT NULL,
    gebruiker_id    BIGINT        NOT NULL,
    CONSTRAINT fk_bestelling_gebruiker FOREIGN KEY (gebruiker_id) REFERENCES gebruiker (id)
);

CREATE TABLE IF NOT EXISTS bestelling_regel (
    id              BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bestelling_id   BIGINT         NOT NULL,
    product_id      BIGINT         NOT NULL,
    aantal          INT            NOT NULL,
    eenheidsprijs   DECIMAL(10, 2) NOT NULL,
    CONSTRAINT fk_regel_bestelling FOREIGN KEY (bestelling_id) REFERENCES bestelling (id),
    CONSTRAINT fk_regel_product    FOREIGN KEY (product_id)    REFERENCES product (id)
);
